name: Bug Report
description: Create a bug report for integration_google
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: input
    attributes:
      label: Which version of integration_google are you using?
      description: 'Please specify the exact version instead of "latest". For example: 2.0.2'
    validations:
      required: true
  - type: input
    attributes:
      label: Which version of Nextcloud are you using?
      description: 'For example: v23.0.1'
    validations:
      required: true
  - type: input
    attributes:
      label: Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.
      description: 'Please specify the exact version instead of "latest". For example: Chrome 100.0.4878.0 or '
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear number of steps that always reproduces the issue. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
        Contributors should be able to follow the steps provided in order to reproduce the bug.